name: 'run-Upgrade-script'
description: 'this runs the Upgrade script'

inputs:
  # Required
  mascotDefault:
    description: config_file
    required: true

  # Default
  mascot:
    description: domain
    required: false

runs:
  using: "composite"
  steps:
    - name: Run bootstrap script
      shell: bash
      run:  echo 'Hi ${{ inputs.mascotDefault }}'
    - name: Run bootstrap script
      shell: bash
      run:  echo 'Hi ${{ inputs.mascot }}'
