name: Test Variables
on:
  push:
    branches: 
      - main

permissions:
  contents: read
  pull-requests: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
        matrix:
          environment: [ dev, test ]
          
    environment:  ${{ matrix.environment }}  
    steps:

      # Checks-out the repository under $GITHUB-WORKSPACE 
      - name: Checkout repo
        uses: actions/checkout@v3
        
      # Runs a set of commands using the runners Shell (Running a Python Script)     
      - name: Echo the message
        uses: gchacon054/git-tutorial/.github/actions/deploy@main
        with:
          mascotRequired: "Mascot Required"     #Override all
          mascot: ${{vars.mascot}}              #Will take values from environment.variables
          #mascotValueDefault without value to take default from actions
          domain_password: "***"
          build_server: ${{ vars.BUILD_SERVER }} 
          domain: ${{ vars.DOMAIN }} 
          domain_username: ${{ vars.DOMAIN_USERNAME }} 
          full: ${{ vars.FULL }}
          git_remote: ${{ vars.GIT_REMOTE }} 
          http_proxy: ${{ vars.HTTP_PROXY }} 
          installers_path: ${{ vars.INSTALLERS_PATH }} 
          repository_root: ${{ vars.REPOSITORY_ROOT }}
          skip_git_pull: ${{ vars.SKIP_GIT_PULL }} 
          tunnel_via: ${{ vars.TUNNEL_VIA }} 
