name: Test Variables
on:
  push:
    branches: 
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
        matrix:
          environment: [ dev, test ]
          
    environment:  ${{ matrix.environment }}  
    steps:

      # Checks-out the repository under $GITHUB-WORKSPACE 
      - name: Checkout repo
        uses: actions/checkout@v3
        
      # Runs a set of commands using the runners Shell (Running a Python Script)     
      - name: Echo the message
        uses: gchacon054/git-tutorial/.github/actions/deploy@main
        with:
          #mascotRequired: "Mascot Required"    #Override all
          mascot: ${{vars.mascot}}   #Will take values from environment.variables
          #mascotValueDefault without value to take default from actions
